/* Generated by Together */

package org.processmining.plugins.declareminer.visualizing;


public class ActivityDefinition extends Base {

	protected static final String DURATION = "duration";

	private AssignmentModel assignmentModel;

	private String name;
	
//	private boolean visible;
//
//	public boolean isVisible() {
//		return visible;
//	}
//
//	public void setVisible(boolean visible) {
//		this.visible = visible;
//	}

	/*
	 * externalSpecification and externalDecomposition are used for launching a
	 * YAWL case for this activity (instead letting DECLARE users execute the
	 * activity in DECLARE WORKLIST). externalSpecification is the
	 * specificationId in a YAWL model (e.g., "test.ywl"). externalDecomposition
	 * is the decompositionId of the net in the same YALW model (e.g., "main").
	 * 
	 * externalSpecification and externalDecomposition are optional fields. if
	 * externalSpecification and/or externalDecomposition are null, then this
	 * activity is not forwarded to YAWL
	 */
	//protected ExternalCase externalCase = null;
	protected boolean external;

	/**
	 * ActivityDefinition
	 * 
	 * @param anId
	 *            int
	 * @param model
	 *            AssignmentModel
	 */
	public ActivityDefinition(int anId, AssignmentModel model) {
		super(anId);
		name = "";
		assignmentModel = model;
	//	setExternal(false);

	}

	/**
	 * ActivityDefinition
	 * 
	 * @param anName
	 *            String
	 * @param anId
	 *            int
	 * @param model
	 *            AssignmentModel
	 */
	public ActivityDefinition(String anName, int anId, AssignmentModel model) {
		this(anId, model);
		name = anName;
	}

	/**
	 * ActivityDefinition
	 * 
	 * @param model
	 *            AssignmentModel
	 * @param definition
	 *            int
	 */
	public ActivityDefinition(AssignmentModel model, ActivityDefinition definition) {
		super(definition);
		name = definition.getName();
		assignmentModel = model;
	//	setExternal(definition.isExternal());
		//if (definition.externalCase != null) {
		//	externalCase = (ExternalCase) definition.externalCase.clone();
		//}

	}

	/**
	 * equals
	 * 
	 * @param anObject
	 *            Object
	 * @return boolean
	 */
	public boolean equals(Object anObject) {
		boolean result = false;
		if (anObject != null) {
			if (anObject instanceof ActivityDefinition) {
				ActivityDefinition anActivityDefinition = (ActivityDefinition) anObject;
				result = ((anActivityDefinition.getId() == getId()) || (anActivityDefinition.getName()
						.equals(getName())));
			}
		}
		return result;
	}

	public int hashCode() {
		return getId();
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		return name;
	}

	/**
	 * clone
	 * 
	 * @return Object
	 */
	public Object clone() {
		ActivityDefinition clone = new ActivityDefinition(getName(), getId(), assignmentModel);
	//	clone.setExternal(isExternal());
	//	if (externalCase != null) {
	//		clone.externalCase = (ExternalCase) externalCase.clone();
	//	}

		return clone;
	}

	/**
	 * setName
	 * 
	 * @param name
	 *            String
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * getName
	 * 
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * getModel
	 * 
	 * @return AssignmentModel
	 */
	public AssignmentModel getAssignmentModel() {
		return assignmentModel;
	}

	/**
	 * setModel
	 * 
	 * @param model
	 *            AssignmentModel
	 */
	protected void setAssignmentModel(AssignmentModel model) {
		assignmentModel = model;
	}

//	public void setExternal(boolean external) {
//		if ((!this.external) && external) {
//			externalCase = new ExternalCase();
//		}
//		;
//		if (!external) {
//			externalCase = null;
//		}
//		this.external = external;
//	}

	public boolean isExternal() {
		return external;
	}

//	public ExternalCase getExternalCase() {
//		return externalCase;
//	}

}
